package helpers

const (
	ERR_TOKEN_EXPIRED  = "TOKEN HAS EXPIRED"
	ERR_TOKEN_SIGNIN   = "SIGN IN FIRST"
	ERR_VALIDATE_EMAIL = "FAILED VALIDATE EMAIL"
	ERR_CREATE_USER    = "FAILED TO CREATE USER"
	ERR_EXIST          = "USER ALREADY EXIST"
	ERR_UNAUTHORIZED   = "UNAUTHORIZED"
	ERR_INVALID_PASS   = "INVALID EMAIL / PASSWORD"
	ERR_GET_INFO       = "FAILED TO GET USER INFO"
	ERR_SUBSCRIPTION   = "FAILED TO UPDATE SUBSCRIPTION"
	ERR_NOT_FOUND      = "USER NOT FOUND"
	ERR_LIMIT          = "OUT OF LIMIT"
	ERR_SWIPE          = "ALREADY SWIPE"
	ERR_CHECK_EXIST    = "FAILED TO CHECK EXIST KEY"
	ERR_CHECK_TOTAL    = "FAILED TO CHECK TOTAL KEY"
	ERR_SET_KEY        = "FAILED TO SET REDIS"
)
